# Generated by Django 5.2.5 on 2025-08-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorcher_received', models.PositiveIntegerField(max_length=10)),
                ('vorcher_sold', models.PositiveBigIntegerField(max_length=10)),
                ('vorcher_remaining', models.PositiveBigIntegerField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Today',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorcher_no', models.PositiveIntegerField(max_length=10)),
                ('date_dist', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
