# Generated by Django 5.2.5 on 2025-08-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='vorcher_received',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='money',
            name='vorcher_sold',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='today',
            name='vorcher_no',
            field=models.PositiveIntegerField(),
        ),
    ]
