# Generated by Django 5.2.5 on 2025-08-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_alter_money_vorcher_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='price_type',
            field=models.CharField(choices=[('v_1K', '1K'), ('v_1.5k', '1.5K'), ('v_6k', '6K'), ('v_25k', '25K')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='money',
            name='vorcher_remaining',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='money',
            name='vorcher_sold',
            field=models.PositiveIntegerField(),
        ),
    ]
