# Generated by Django 5.2.5 on 2025-08-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_money_price_type_alter_money_vorcher_remaining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='vorcher_remaining',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
